baseURL = "https://maxatlas.github.io/"
languageCode = "en-us"
title = "MaxAtlas"
theme = "maxatlas"

[taxonomies]
  series = "series"
  tag = "tags"

[params]
  description = "Dev articles with a gaming soul"

[pagination]
  pagerSize = 10
